### ISSUE TITLE
Still having issues uploading new version to API

### ISSUE THREAD

**Issue by mazondo** [sendwithus/grunt-sendwithus#3]
No errors are getting reported.  The issue seems to be inside the requestp function.  If you add a log to the start of it, it'll get triggerred, but if you add one to the response callback, it never triggers:

<img width="709" alt="screen shot 2016-06-20 at 8 48 35 pm" src="https://cloud.githubusercontent.com/assets/36265/16216494/650d8872-3728-11e6-9062-c895b8c7419c.png">

**Comment by mazondo** [comment]
You can see here that it triggers the update log, but never triggers the complete log:

<img width="949" alt="screen shot 2016-06-20 at 8 52 42 pm" src="https://cloud.githubusercontent.com/assets/36265/16216573/0037b944-3729-11e6-9759-3df1c876a78b.png">

**Comment by mazondo** [comment]
Confirmed this issue on the newest branch `0.1.0` as well

**Comment by brandonb927** [comment]
@mazondo I can take a look at this again. Can you do me a favour though and delete the `grunt-sendwithus.json` file in your home folder then run the grunt task again? I'm curious if your local cache might be corrupt...

**Comment by mazondo** [comment]
Hi brandon.  I did actually do that, but it caused duplicates of all our templates in our account, so sorting through that now :)

BUT, it did upload them.  Not sure yet if updating will work though.

**Comment by brandonb927** [comment]
Ah, sorry about that. There isn't really a way to detect if there are duplicates because you can have templates with duplicated content (intentionally), but they could be completely different templates.

Let me know if updating is working and if not, I will dive into it again.

**Comment by brandonb927** [comment]
@mazondo I see the ticket you raised in the Sendwithus live chat so I'm going to close this ticket until we issue a new release
